version: "3"
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 173.20.0.0/24


services: 
    php:
        build: ./
        volumes:     
            - ./testProject:/var/www/html/
            - ./testProject/confphp/php.ini:/usr/local/etc/php/php.ini

        ports:
            - 8081:8081 
        command: php -S 173.20.0.3:8081    

        networks:
            mynetwork:
                ipv4_address: 173.20.0.3

    database:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        volumes:
            - /db:/var/lib/postgresql/data:rw
        ports:
            - "5432:5432"

        networks:
            mynetwork:
                ipv4_address: 173.20.0.5    


    encore:
        image: node:19-alpine
        volumes:
            - ./testProject:/app:rw
            - ./testProject/node_modules:/usr/app/node_modules
        ports:
            - "8082:8080"
        working_dir: /app
        command: ["yarn", "install"] 

        networks:
            mynetwork:
                ipv4_address: 173.20.0.7            



    adminer:
        image: adminer
        ports:
           - 8080:8080   
        networks:
            mynetwork:
                ipv4_address: 173.20.0.6  

    typesense:
        image: typesense/typesense:0.23.1
        ports:
            - "8108:8108"
  
        environment:
            TYPESENSE_DATA_DIR: /data
            TYPESENSE_API_KEY: a00c45f7-808e-4e66-8e1f-cf73a334c452               

        volumes:
            - ./testProject/data:/data 
        networks:
            mynetwork:
                ipv4_address: 173.20.0.4      

    golang:
        build: 
            context: . 
            dockerfile: ./sync.Dockerfile
        volumes:
            - ./sync-stations:/go/src/app:rw
        ports:
            - 4002:8080
        command: go run cmd/main.go

        networks:
            mynetwork:
                ipv4_address: 173.20.0.10
                
                   

  
    
